global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

   

# Новый job для нашего приложения 

  - job_name: "web_application"
    static_configs: 
      - targets: ["localhost:5000"] 
    scrape_interval: 10s 
    metrics_path: '/metrics'


# Новая секция для алертинга
alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - localhost:9093

# Загрузка правил алертов
rule_files:
  - "alert_rules.yml"
